In [5]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print (x+y)# 加法
print (x*y) #乘法
print (x-y) #减法
print (x/y) #除法

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[-5 -5 -5 -5 -5]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [7]:
import numpy as np
x = np.array([[1,2],[3,4]])
print (x*10)

[[10 20]
 [30 40]]
